### ISSUE TITLE
duplicate equality lemmas

### ISSUE THREAD

**Issue by fpvandoorn** [gebner/hott3#4]
Do we need the lemmas in https://github.com/gebner/hott3/blob/master/init/path.lean#L26-L56? All of them are defined a second time in that file with their "HoTT-name". However, just removing them causes `hsimp` to break. Are these names hardcoded in the `simp` framework? If so, then we can leave them (we probably shouldn't use `hsimp` whenever we care about the exact term which is produced, so it shouldn't really matter that it uses `subst`/`mp`/`congr_arg`/... instead of `transport`/`cast`/`ap`/...)

**Comment by gebner** [comment]
AFAICT, the only hardcoded name is `hott.eq.mp`, and I just replaced that by `hott.eq.cast`.  The only other important definition is `congr`, which is found via the `[congr]` attribute.

The rewrite/reflexivity/symmetry/transitivity tactics already use `ap` and co.

**Comment by fpvandoorn** [comment]
Thanks! I also pointed the `[congr]` attribute also to the HoTT-version `ap11`.
