### ISSUE TITLE
make idp_rec_on a recursor

### ISSUE THREAD

**Issue by fpvandoorn** [gebner/hott3#5]
Do you know why [`idp_rec_on`](https://github.com/gebner/hott3/blob/13f78ac3b561f99da323200da1987253edb539eb/init/pathover.lean#L194) [link] is not accepted as a recursor? The error is 
```
invalid user defined recursor, motive result sort must be Prop or Type.{l} where l is a universe parameter
```
but the motive result sort is `Type u_2`, so I think that should be fine.

PS: let me know if I'm opening too much of these issues or if you prefer another line of communication

**Comment by gebner** [comment]
This is an old error message from before we renamed `Type` to `Sort`.  That is, it should read "`Prop` or `Sort l`".  Changing the motive of `transport` and `idp_rec_on` to eliminate into `Sort` makes Lean accept it as a recursor.

I don't mind the issues.

**Comment by fpvandoorn** [comment]
Ah, that makes sense.

If I do that though, I get the `deep recursion was detected at 'whnf'` error message when applying `idp_rec_on`. It happens even without using the `induction` tactic, but it doesn't happen if `idp_rec_on` is not marked as recursor.
See https://github.com/fpvandoorn/hott3/blob/idp_rec_on/init/pathover.lean#L217-L224

**Comment by gebner** [comment]
This is a bug in the VM compiler.  It expects all auxiliary recursors to be reducible.

**Comment by fpvandoorn** [comment]
Thanks!
