### ISSUE TITLE
coercion from pType to Type

### ISSUE THREAD

**Issue by fpvandoorn** [gebner/hott3#7]
If I create a new file with the following code:
```lean
import .init

namespace hott
hott_theory
open hott.pointed

set_option trace.class_instances true
  @[hott, hsimp] def coe_pType_mk (A : Type _) (a : A) : 
    ↥{pType . carrier := A, Point := a} = A := 
  by refl
end hott
```
I get the trace message `[class_instances] cached failure for has_coe_to_sort Type*`. Any idea why?

Second question: is the best way to reduce these expressions to use `dsimp` with an `hsimp` lemma like this?

**Comment by gebner** [comment]
This is an interesting error message, I don't see any obvious reason why it fails.  I don't think plain `coe_sort` is used anywhere.

As a workaround, you can let the elaborator figure out the coercions:
```lean
  @[hott, hsimp] def coe_pType_mk (A : Type _) (a : A) :
    (({pType . carrier := A, Point := a}: _): Type _) = A :=
  by refl
```

Yes, I think that's the best way to reduce coerced values at the moment.
